# Generated by Django 6.0.1 on 2026-01-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
