# Generated by Django 6.0.1 on 2026-01-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productvariant_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
