# Generated by Django 6.0.1 on 2026-01-18 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productvariant_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
